---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    data_bags_path: test/fixtures/default/data_bags
    run_list:
      - recipe[base::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
